project_id: 307981
base_path: .
preserve_hierarchy: 
files:
  - source: /translations/locales/en.json
    translation: /translations/locales/%locale_with_underscore%.json
  - source: /ios/swc/Base.lproj/*.*
    ignore:
      - /ios/swc/Base.lproj/*.xib
    translation: /ios/swc/%osx_code%/%original_file_name%
  - source: /android/app/src/main/res/values/strings.xml
    translation: /android/app/src/main/res/values-%android_code%/%original_file_name%
